# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0378bI90OQBvHCjnD0scZXrYDCAETrM
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.tail()

df.info()

df.columns

df.describe()

df.shape

columns_to_drop = ["Timestamp", "Country", "care_options"]
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors='ignore')

df.columns

df.shape

df.isnull().sum()

df[df["self_employed"]=="No"].head(50)

df[df["self_employed"] == "Yes"].head(50)

df[df["self_employed"].isna()].head(40)

df[(df["self_employed"] == "Yes") & (df["Social_Weakness"] == "Yes")]

df[(df["Occupation"] == "Others") & (df["Work_Interest"] == "Yes")&  (df["Mood_Swings"] == "Low")& (df["Social_Weakness"] == "Yes")]

df[(df["self_employed"] == "Yes") & (df["Occupation"].isin(["Student", "Housewife"])) & (df["Work_Interest"] == "No")]

df[(df["self_employed"] == "Yes") & (df["Occupation"] == "Student")&(df["Work_Interest"] .isin(["Maybe"]))& (df["Social_Weakness"] == "Yes")& (df["Mental_Health_History"] == "Yes")]

df[(df["self_employed"] == "No") &
   (df["Occupation"] == "Business") &
   (df["Gender"] == "Female") &
   (df["Work_Interest"].isin([ "Maybe"])) &
   (df["Changes_Habits"].isin(["No", "Maybe", "Yes"]))]

df.loc[(df["Occupation"].isin(["student", "Housewife"])) |(df["Work_Interest"] == "No"), "self_employed"] = "No"

df.isnull().sum()

df.loc[(df["Occupation"] == "Business") &
       (df["Work_Interest"].isin(["Maybe", "Yes"])) &
       (df["Gender"].isin(["Female", "Male"])) &
       (df["Changes_Habits"].isin(["No", "Maybe", "Yes"])), "self_employed"] = "Yes"

df.isnull().sum()

df.loc[(df["Occupation"] == "Business") & (df["Work_Interest"].isin(["Maybe", "Yes"])), "self_employed"] = "Yes"

df.isnull().sum()

df.loc[(df["Occupation"].isin(["Student", "Housewife"])) | (df["Work_Interest"] == "No"), "self_employed"] = "No"

df.loc[(df["Occupation"] == "Other") &
       (df["Work_Interest"].isin(["Yes", "Maybe"])) &
       (df["Social_Weakness"] == "No"), "self_employed"] = "Yes"

df.loc[(df["Occupation"].isin(["Other", "Business"])) &
       (df["Work_Interest"].isin(["Maybe", "Yes"])) &
       (df["Social_Weakness"].isin(["No", "Maybe"])), "self_employed"] = "Yes"

df.loc[(df["Occupation"] == "Business") &
       (df["Work_Interest"].isin(["Maybe", "Yes"])) &
       (df["Gender"].isin(["Female", "Male"])) &
       (df["Changes_Habits"].isin(["No", "Maybe", "Yes"])), "self_employed"] = "Yes"

df.isnull().sum()

def fill_self_employed(row):
    # Case 1
    if row["Occupation"] in ["Student", "Housewife"] or row["Work_Interest"] == "No":
        return "No"

    # Case 2
    elif row["Occupation"] == "Others" and row["Work_Interest"] in ["Yes", "Maybe"] and row["Social_Weakness"] == "No":
        return "Yes"

    # Case 3
    elif row["Occupation"] in ["Others", "Business"] and row["Work_Interest"] in ["Maybe", "Yes"] and row["Social_Weakness"] in ["No", "Maybe"]:
        return "Yes"

    # Case 4
    elif row["Occupation"] == "Business" and row["Work_Interest"] in ["Maybe", "Yes"] and row["Gender"] in ["Female", "Male"] and row["Changes_Habits"] in ["No", "Maybe", "Yes"]:
        return "Yes"

    # Case 5
    elif row["Occupation"] in ["Corporate", "Others"] and row["Gender"] in ["Male", "Female"] and row["Work_Interest"] == "Yes":
        return "Yes"

    # Case 6
    elif row["Occupation"] == "Others" and row["family_history"] in ["Yes", "Maybe"] and row["Work_Interest"] in ["Yes", "Maybe"] and row["Social_Weakness"] in ["No", "Maybe"]:
        return "Yes"

    # Case 7
    elif row["Occupation"] == "Others" and row["family_history"] == "Yes" and row["Gender"] in ["Male", "Female"] and row["Work_Interest"] in ["No", "Maybe"] and row["Social_Weakness"] in ["Yes", "Maybe"]:
        return "No"

    # Case 8
    elif row["Occupation"] == "Others" and row["Mental_Health_History"] == "Yes" and row["Growing_Stress"] == "Yes" and row["Coping_Struggles"] == "High":
        return "No"

    # Case 9
    elif row["Occupation"] in ["Corporate", "Others"] and row["Changes_Habits"] in ["Yes", "Maybe"] and row["Days_Indoors"] in ["More than 2 months", "31-60 days"]:
        return "Yes"

    # Case 10
        return "Yes"

    # Case 11
    elif row["Occupation"] == "Others" and row["Growing_Stress"] == "Yes" and row["Work_Interest"] == "Maybe" and row["family_history"] in ["Yes", "Maybe"]:
        return "Yes"

    # Case 12
    else:
        return "No"


df["self_employed"] = df.apply(fill_self_employed, axis=1)

df.isnull().sum()