# -*- coding: utf-8 -*-
"""fillna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTm_QC-5xOi7GDCj4aaKM0ZPOeVqXx4R
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.tail()

df.isnull().sum()

mode_value = df['self_employed'].mode()[0]
df['self_employed'].fillna(mode_value, inplace=True)

df.isnull().sum()