# -*- coding: utf-8 -*-
"""fillna 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyURXMb3-LDarhgNxWCgRa36oiR5NLbE
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.tail()

df.isnull().sum()

df['self_employed'].fillna('Unknown', inplace=True)

df.isnull().sum()